Web Scraping from Financial TImes Websites

In [12]:
#Import Libraries for Web Scraping
import requests
import pandas as pd
from bs4 import BeautifulSoup
from datetime import timedelta, date, datetime

In [13]:
#Get data from current time in format (2023-10-30 213030)
current_time = datetime.now()
format_date_time = current_time.strftime("%Y-%m-%d %H%M%S")

In [14]:
#Scrape from URL 
url_to_scrape = 'https://markets.ft.com/data/equities/tearsheet/profile?s=KNM:KLS'

#to keep information by using request library
s_request = requests.session()

#GET request to the URL to send back the content of the web page 
soup_content = s_request.get(url_to_scrape)

In [15]:
#he parser used to parse the HTML content to soup_content in structured content
soup_content = BeautifulSoup(soup_content.content, 'html.parser')

In [6]:
#save parsed HTML
with open (format_date_time+".html" , "w", encoding='utf-8') as files_f:
    files_f.write(str(soup_content))
    files_f.close()

In [16]:
#find table element within HTML content (soup_content)
#"table" - search for table element 
table = soup_content.find("table", attrs={"class":"mod-ui-table mod-ui-table--freeze-pane"} )

In [17]:
#collect headers of table that often siplaying titles for column
header = table.find_all('th')

In [18]:
#Display headers of table
header

[<th class="mod-ui-table__header--text">Company</th>,
 <th data-mod-view-category="keyinformation">Revenue (TTM)</th>,
 <th data-mod-view-category="keyinformation">Net income (TTM)</th>,
 <th data-mod-view-category="keyinformation">Market cap</th>,
 <th data-mod-view-category="keyinformation">Employees</th>,
 <th data-mod-view-category="stockperformance">Price/earnings (TTM)</th>,
 <th data-mod-view-category="stockperformance">Price/book value (MRQ)</th>,
 <th data-mod-view-category="stockperformance">Price/cash flow (TTM)</th>,
 <th data-mod-view-category="stockperformance">Price/sales (TTM)</th>,
 <th data-mod-view-category="persharedata">EPS (excl. extraordinary items, TTM)</th>,
 <th data-mod-view-category="persharedata">EPS (incl. extraordinary items, TTM)</th>,
 <th data-mod-view-category="persharedata">Revenue per share (TTM)</th>,
 <th data-mod-view-category="persharedata">Book value per share (MRQ)</th>,
 <th data-mod-view-category="efficiency">Asset turnover (TTM)</th>,
 <th data-mod-view-category="efficiency">Inventory turnover (TTM)</th>,
 <th data-mod-view-category="efficiency">Receivables turnover (TTM)</th>,
 <th data-mod-view-category="efficiency">Revenues per employee (TTM)</th>,
 <th data-mod-view-category="managementeffectiveness">Return on avg assets (TTM)</th>,
 <th data-mod-view-category="managementeffectiveness">Return on avg assets (5 yr avg)</th>,
 <th data-mod-view-category="managementeffectiveness">Return on investment (TTM)</th>,
 <th data-mod-view-category="managementeffectiveness">Return on investment (5 yr avg)</th>,
 <th data-mod-view-category="profitability">Gross margin (TTM)</th>,
 <th data-mod-view-category="profitability">Gross margin<br/>(5 yr avg)</th>,
 <th data-mod-view-category="profitability">Net profit margin (TTM)</th>,
 <th data-mod-view-category="profitability">Net Profit margin<br/>(5 yr avg)</th>,
 <th data-mod-view-category="financialstrength">Quick ratio (MRQ)</th>,
 <th data-mod-view-category="financialstrength">Interest coverage (TTM)</th>,
 <th data-mod-view-category="financialstrength">Total debt to capital (MRQ)</th>,
 <th data-mod-view-category="financialstrength">Payout ratio<br/>(5 yr avg)</th>,
 <th data-mod-view-category="growthrates">Revenue<br/>(YOY change %)</th>,
 <th data-mod-view-category="growthrates">Revenue<br/>(5 yr growth rate)</th>,
 <th data-mod-view-category="growthrates">Net income<br/>(YOY change %)</th>,
 <th data-mod-view-category="growthrates">Net income<br/>(5 yr growth rate)</th>,
 <th data-mod-view-category="growthrates">Capital expenditure<br/>(5 yr growth rate)</th>,
 <th data-mod-view-category="growthrates">Dividend<br/>(5 yr growth rate)</th>]

In [19]:
#define function get_header to list down HTML table header
def get_header(tr):
    #empty list to store extracted text from the header cells
    table_headers = []
    #starts a loop that iterates through each table header element in the list 'tr'
    #each header element is temporarily assigned to the variable 'tx'
    for tx in tr:
        #extract table headers element in a list
        table_headers.append(tx.get_text())

    return table_headers

all_headerow = get_header(header)

In [22]:
all_headerow

['Company',
 'Revenue (TTM)',
 'Net income (TTM)',
 'Market cap',
 'Employees',
 'Price/earnings (TTM)',
 'Price/book value (MRQ)',
 'Price/cash flow (TTM)',
 'Price/sales (TTM)',
 'EPS (excl. extraordinary items, TTM)',
 'EPS (incl. extraordinary items, TTM)',
 'Revenue per share (TTM)',
 'Book value per share (MRQ)',
 'Asset turnover (TTM)',
 'Inventory turnover (TTM)',
 'Receivables turnover (TTM)',
 'Revenues per employee (TTM)',
 'Return on avg assets (TTM)',
 'Return on avg assets (5 yr avg)',
 'Return on investment (TTM)',
 'Return on investment (5 yr avg)',
 'Gross margin (TTM)',
 'Gross margin(5 yr avg)',
 'Net profit margin (TTM)',
 'Net Profit margin(5 yr avg)',
 'Quick ratio (MRQ)',
 'Interest coverage (TTM)',
 'Total debt to capital (MRQ)',
 'Payout ratio(5 yr avg)',
 'Revenue(YOY change %)',
 'Revenue(5 yr growth rate)',
 'Net income(YOY change %)',
 'Net income(5 yr growth rate)',
 'Capital expenditure(5 yr growth rate)',
 'Dividend(5 yr growth rate)']

In [24]:
#get all data in rows table 
all_tr_in_table = table.find_all('tr')
# print(all_tr_in_table)
def get_row(tr):
    row = []
    for tx in tr:
        table_headers = []
        _data = tx.find_all('td')
        for _xx in _data:
            table_headers.append(_xx.get_text())

        row.append(table_headers)
    return row

#sent argument to get_row funtion
data = get_row(all_tr_in_table)

In [26]:
data

[['Carimin Petroleum Bhd',
  '254.74m',
  '23.11m',
  '199.97m',
  '--',
  '8.76',
  '1.04',
  '6.71',
  '0.7942',
  '0.0988',
  '0.0988',
  '1.09',
  '0.8294',
  '0.909',
  '--',
  '2.84',
  '--',
  '8.23',
  '5.43',
  '12.31',
  '8.62',
  '18.82',
  '13.73',
  '9.05',
  '5.62',
  '--',
  '10.36',
  '0.0315',
  '20.15',
  '11.85',
  '12.51',
  '253.11',
  '--',
  '99.36',
  '--'],
 ['Uzma Berhad',
  '474.02m',
  '38.99m',
  '290.42m',
  '748.00',
  '6.77',
  '0.4891',
  '3.16',
  '0.6127',
  '0.1108',
  '0.1108',
  '1.35',
  '1.53',
  '0.3636',
  '5.89',
  '1.30',
  '--',
  '3.09',
  '0.9159',
  '4.99',
  '1.36',
  '41.97',
  '34.11',
  '8.51',
  '2.55',
  '1.05',
  '3.78',
  '0.4207',
  '--',
  '25.42',
  '--',
  '672.78',
  '--',
  '--',
  '--'],
 ['Icon Offshore Bhd',
  '236.06m',
  '158.82m',
  '324.78m',
  '537.00',
  '1.96',
  '0.8493',
  '1.42',
  '1.32',
  '0.0587',
  '0.0587',
  '0.0873',
  '0.1354',
  '0.2776',
  '258.34',
  '2.40',
  '439,582.20',
  '18.99',
  '-5.17',
  '24.79',
  '-9.72',
  '18.37',
  '28.29',
  '68.41',
  '-18.69',
  '2.33',
  '9.14',
  '0.408',
  '--',
  '-5.69',
  '6.74',
  '644.25',
  '--',
  '-3.09',
  '--'],
 ['T7 Global Bhd',
  '446.10m',
  '25.65m',
  '345.37m',
  '442.00',
  '13.50',
  '1.12',
  '--',
  '0.7827',
  '0.0341',
  '0.0341',
  '0.6031',
  '0.41',
  '0.4463',
  '1.87',
  '4.63',
  '--',
  '2.50',
  '2.37',
  '3.71',
  '3.53',
  '26.76',
  '20.60',
  '5.59',
  '4.57',
  '0.4209',
  '5.03',
  '0.7128',
  '4.60',
  '18.81',
  '12.16',
  '92.75',
  '60.97',
  '78.00',
  '--'],
 ['Deleum Bhd',
  '780.48m',
  '44.43m',
  '399.55m',
  '592.00',
  '9.40',
  '1.06',
  '4.63',
  '0.5351',
  '0.1106',
  '0.1106',
  '1.94',
  '0.9826',
  '1.35',
  '29.98',
  '5.09',
  '1,318,371.00',
  '9.86',
  '5.06',
  '14.30',
  '8.78',
  '19.80',
  '18.87',
  '7.33',
  '5.04',
  '2.54',
  '--',
  '0.0066',
  '46.99',
  '25.02',
  '5.50',
  '120.50',
  '5.34',
  '26.62',
  '4.32'],
 ['Perdana Petroleum Bhd',
  '235.90m',
  '32.32m',
  '532.83m',
  '937.00',
  '17.63',
  '0.8757',
  '6.21',
  '2.35',
  '0.0142',
  '0.0142',
  '0.1052',
  '0.2855',
  '0.2771',
  '22.58',
  '3.38',
  '--',
  '3.80',
  '-7.74',
  '4.25',
  '-11.56',
  '31.25',
  '-1.47',
  '13.70',
  '-45.20',
  '1.60',
  '4.55',
  '0.0546',
  '--',
  '28.12',
  '5.88',
  '103.47',
  '--',
  '36.30',
  '--'],
 ['KNM Group Berhad',
  '585.50m',
  '-201.09m',
  '687.80m',
  '834.00',
  '--',
  '0.6777',
  '--',
  '1.00',
  '-0.056',
  '-0.0436',
  '0.1604',
  '0.214',
  '0.1822',
  '--',
  '1.26',
  '--',
  '-6.78',
  '--',
  '-18.19',
  '--',
  '--',
  '--',
  '-37.20',
  '--',
  '0.6061',
  '-0.7927',
  '0.6183',
  '--',
  '--',
  '--',
  '--',
  '--',
  '--',
  '--'],
 ['Wasco Bhd',
  '2.81bn',
  '17.09m',
  '724.52m',
  '3.87k',
  '43.03',
  '1.18',
  '6.27',
  '0.2622',
  '0.0221',
  '0.0221',
  '3.63',
  '0.8037',
  '1.03',
  '10.97',
  '2.76',
  '726,373.60',
  '1.65',
  '-2.35',
  '4.70',
  '-5.21',
  '14.25',
  '12.76',
  '1.61',
  '-2.75',
  '0.8222',
  '2.37',
  '0.5797',
  '--',
  '87.96',
  '1.51',
  '94.14',
  '--',
  '-40.17',
  '--'],
 ['Sapura Energy Bhd',
  '4.59bn',
  '-3.06bn',
  '798.95m',
  '2.44k',
  '--',
  '--',
  '--',
  '0.1916',
  '-0.1914',
  '-0.1914',
  '0.2871',
  '-0.1865',
  '0.3014',
  '--',
  '2.76',
  '1,880,762.00',
  '-20.24',
  '-16.91',
  '--',
  '-28.37',
  '--',
  '-4.92',
  '-67.14',
  '-78.66',
  '0.1578',
  '0.3255',
  '1.38',
  '--',
  '11.00',
  '-2.06',
  '65.11',
  '--',
  '-28.98',
  '--'],
 ['Malaysia Marine and Heavy Engg Hldgs Bhd',
  '2.39bn',
  '-342.08m',
  '840.00m',
  '3.37k',
  '--',
  '0.6557',
  '--',
  '0.3655',
  '-0.2138',
  '-0.2138',
  '1.49',
  '0.8312',
  '0.6907',
  '--',
  '2.47',
  '708,994.90',
  '-9.91',
  '-4.70',
  '-18.68',
  '-6.61',
  '--',
  '6.07',
  '-14.35',
  '-11.49',
  '0.9061',
  '-25.57',
  '0.195',
  '--',
  '12.56',
  '11.55',
  '125.06',
  '14.64',
  '-7.61',
  '-12.94'],
 ['Velesto Energy Bhd',
  '983.42m',
  '20.59m',
  '2.01bn',
  '722.00',
  '103.59',
  '0.8942',
  '10.27',
  '2.17',
  '0.0025',
  '0.0025',
  '0.1197',
  '0.2908',
  '0.3163',
  '--',
  '3.78',
  '1,362,072.00',
  '0.6621',
  '-3.52',
  '0.7789',
  '-3.94',
  '--',
  '87.41',
  '2.09',
  '-24.38',
  '0.9858',
  '2.12',
  '0.1804',
  '--',
  '53.86',
  '-0.1985',
  '-10.55',
  '--',
  '53.71',
  '--'],
 ['Dayang Enterprise Holdings Berhad',
  '978.79m',
  '114.16m',
  '2.12bn',
  '2.16k',
  '18.76',
  '1.42',
  '9.24',
  '2.19',
  '0.0986',
  '0.0986',
  '0.8454',
  '1.31',
  '0.4049',
  '55.18',
  '2.39',
  '452,933.40',
  '5.21',
  '0.6648',
  '6.83',
  '1.00',
  '35.86',
  '34.80',
  '12.86',
  '2.02',
  '2.51',
  '4.89',
  '0.1798',
  '13.78',
  '47.39',
  '7.21',
  '138.28',
  '--',
  '14.08',
  '--'],
 ['Bumi Armada Bhd',
  '2.24bn',
  '680.18m',
  '3.17bn',
  '879.00',
  '4.70',
  '0.5513',
  '3.22',
  '1.43',
  '0.115',
  '0.115',
  '0.3792',
  '0.9795',
  '0.187',
  '--',
  '3.99',
  '2,552,232.00',
  '5.45',
  '-1.19',
  '6.47',
  '-1.66',
  '45.27',
  '35.63',
  '29.15',
  '-7.30',
  '--',
  '3.28',
  '0.4597',
  '--',
  '11.23',
  '0.0284',
  '11.10',
  '15.77',
  '-75.87',
  '--']]

In [27]:
# pd.set_option('expand_frame_repr', False) # gunakan ini untuk print DataFrame dalam satu barisan
df_table = pd.DataFrame(data)
df_table.columns = all_headerow
print(df_table)
df_table.to_csv("WebSraping.csv")

                                     Company Revenue (TTM) Net income (TTM)  \
0                      Carimin Petroleum Bhd       254.74m           23.11m
1                                Uzma Berhad       474.02m           38.99m
2                          Icon Offshore Bhd       236.06m          158.82m
3                              T7 Global Bhd       446.10m           25.65m
4                                 Deleum Bhd       780.48m           44.43m
5                      Perdana Petroleum Bhd       235.90m           32.32m
6                           KNM Group Berhad       585.50m         -201.09m
7                                  Wasco Bhd        2.81bn           17.09m
8                          Sapura Energy Bhd        4.59bn          -3.06bn
9   Malaysia Marine and Heavy Engg Hldgs Bhd        2.39bn         -342.08m
10                        Velesto Energy Bhd       983.42m           20.59m
11         Dayang Enterprise Holdings Berhad       978.79m          114.16m
12                           Bumi Armada Bhd        2.24bn          680.18m

   Market cap Employees Price/earnings (TTM) Price/book value (MRQ)  \
0     199.97m        --                 8.76                   1.04
1     290.42m    748.00                 6.77                 0.4891
2     324.78m    537.00                 1.96                 0.8493
3     345.37m    442.00                13.50                   1.12
4     399.55m    592.00                 9.40                   1.06
5     532.83m    937.00                17.63                 0.8757
6     687.80m    834.00                   --                 0.6777
7     724.52m     3.87k                43.03                   1.18
8     798.95m     2.44k                   --                     --
9     840.00m     3.37k                   --                 0.6557
10     2.01bn    722.00               103.59                 0.8942
11     2.12bn     2.16k                18.76                   1.42
12     3.17bn    879.00                 4.70                 0.5513

   Price/cash flow (TTM) Price/sales (TTM)  \
0                   6.71            0.7942
1                   3.16            0.6127
2                   1.42              1.32
3                     --            0.7827
4                   4.63            0.5351
5                   6.21              2.35
6                     --              1.00
7                   6.27            0.2622
8                     --            0.1916
9                     --            0.3655
10                 10.27              2.17
11                  9.24              2.19
12                  3.22              1.43

   EPS (excl. extraordinary items, TTM)  ... Quick ratio (MRQ)  \
0                                0.0988  ...                --
1                                0.1108  ...              1.05
2                                0.0587  ...              2.33
3                                0.0341  ...            0.4209
4                                0.1106  ...              2.54
5                                0.0142  ...              1.60
6                                -0.056  ...            0.6061
7                                0.0221  ...            0.8222
8                               -0.1914  ...            0.1578
9                               -0.2138  ...            0.9061
10                               0.0025  ...            0.9858
11                               0.0986  ...              2.51
12                                0.115  ...                --

   Interest coverage (TTM) Total debt to capital (MRQ) Payout ratio(5 yr avg)  \
0                    10.36                      0.0315                  20.15
1                     3.78                      0.4207                     --
2                     9.14                       0.408                     --
3                     5.03                      0.7128                   4.60
4                       --                      0.0066                  46.99
5                     4.55                      0.0546                     --
6                  -0.7927                      0.6183                     --
7                     2.37                      0.5797                     --
8                   0.3255                        1.38                     --
9                   -25.57                       0.195                     --
10                    2.12                      0.1804                     --
11                    4.89                      0.1798                  13.78
12                    3.28                      0.4597                     --

   Revenue(YOY change %) Revenue(5 yr growth rate) Net income(YOY change %)  \
0                  11.85                     12.51                   253.11
1                  25.42                        --                   672.78
2                  -5.69                      6.74                   644.25
3                  18.81                     12.16                    92.75
4                  25.02                      5.50                   120.50
5                  28.12                      5.88                   103.47
6                     --                        --                       --
7                  87.96                      1.51                    94.14
8                  11.00                     -2.06                    65.11
9                  12.56                     11.55                   125.06
10                 53.86                   -0.1985                   -10.55
11                 47.39                      7.21                   138.28
12                 11.23                    0.0284                    11.10

   Net income(5 yr growth rate) Capital expenditure(5 yr growth rate)  \
0                            --                                 99.36
1                            --                                    --
2                            --                                 -3.09
3                         60.97                                 78.00
4                          5.34                                 26.62
5                            --                                 36.30
6                            --                                    --
7                            --                                -40.17
8                            --                                -28.98
9                         14.64                                 -7.61
10                           --                                 53.71
11                           --                                 14.08
12                        15.77                                -75.87

   Dividend(5 yr growth rate)
0                          --
1                          --
2                          --
3                          --
4                        4.32
5                          --
6                          --
7                          --
8                          --
9                      -12.94
10                         --
11                         --
12                         --

[13 rows x 35 columns]